# @package _global_

defaults:
  - /env: legged_motions
  - /simulator: isaacsim
  - /domain_rand: domain_rand
  - /rewards: reward_bfm_zero
  - /robot: taks_t1/taks_t1_32dof
  - /terrain: terrain_locomotion_plane
  - /obs: bfm_zero_obs
  # - /opt: wandb
  - /callbacks: im_eval

exp_base: ${hydra:runtime.choices.exp}
exp_var: test
experiment_name: ${exp_base}_${exp_var}
experiment_dir: ${base_dir}/${project_name}/${experiment_name}-${timestamp}

num_envs: 50
project_name: BFMZero

robot:
  motion:
    motion_file: data/lafan_29dof.pkl
    max_len: 450
  asset:
    self_collisions: 0

rewards:
  reward_penalty_curriculum: True
  reward_penalty_degree: 0.00001

env:
  config:
    resample_motion_when_training: False
    termination:
      terminate_when_motion_far: False
    termination_curriculum:
      terminate_when_motion_far_curriculum: False
      terminate_when_motion_far_threshold_min: 0.25
      terminate_when_motion_far_threshold_max: 0.5
      terminate_when_motion_far_curriculum_degree: 0.000025
