# @package _global_

# Be careful when using _raw, history
obs:
  use_obs_filter: True
  root_height_obs: True
  obs_dict:
    actor_obs: [
      base_ang_vel,
      projected_gravity,
      dof_pos,
      dof_vel,
      actions,
      history_actor,
      max_local_self,
    ]

    critic_obs: [
      max_local_self
    ]

  obs_auxiliary: # define those coumpounds in obs_dict, for example, you can define different long/short history with different length
    history_actor: {
      base_ang_vel: 4,
      projected_gravity: 4,
      dof_pos: 4,
      dof_vel: 4,
      actions: 4,
    }

  obs_scales: {
    actions: 1.0,
    dof_pos: 1.0,
    dof_vel: 1.0,
    max_local_self: 1.0,
    base_lin_vel: 1.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    history_actor: 1.0,
  }

  noise_scales: {
    base_lin_vel: 0.0,
    base_ang_vel: 0.2,
    projected_gravity: 0.05,
    dof_pos: 0.01,
    dof_vel: 0.5,
    actions: 0.0,
    max_local_self: 0.0,
    history_actor: 0.0,
  }

  add_noise_currculum: False
  noise_initial_value: 0.05
  noise_value_max: 1.0
  noise_value_min: 0.00001
  soft_dof_pos_curriculum_degree: 0.00001
  soft_dof_pos_curriculum_level_down_threshold: 40
  soft_dof_pos_curriculum_level_up_threshold: 42

  obs_dims:
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size}
    - max_local_self: ${eval:'(3 + 6 + 3 + 3) * (${robot.num_bodies} + ${robot.motion.nums_extend_bodies}) + 1 - 3 - 1'}


  post_compute_config: {} # Will store values after preprocessing, don't put anything here