# @package _global_

eval_timestamp: ${now:%Y%m%d_%H%M%S}
eval_name: TEST
eval_motion_id: 0
model_name: "model"
eval_type: "tracking"
eval_log_dir: logs_eval_new/${eval_name}/${eval_timestamp}
hydra:
  run:
    dir: ${eval_log_dir}
