# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Zhengyi
  set_reward_date: 20250320
  only_positive_rewards: False
  reward_scales:
      penalty_torques: -0.000001
      penalty_undesired_contact: -1
      # penalty_dof_vel: -0.0001
      # penalty_dof_acc: -2.5e-8
      penalty_action_rate: -0.5 # need to be tuned up to -0.5 for real robot
      # penalty_feet_contact_forces: -0.01
      # penalty_stumble: -10.0
      penalty_ankle_roll: -0.5
      penalty_feet_ori: -0.1
      # better for landing
      # penalty_feet_ori: -2.0
      feet_heading_alignment: -0.1
      penalty_slippage: -1.0

      limits_dof_pos: -10.0
      limits_dof_vel: -5.0
      limits_torque: -5.0
      # feet_max_height_for_this_air: -100.0
      

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 0.10
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 40
  reward_penalty_level_up_threshold: 42 # shortest motion in TairanTestbed is 92, therefore 46 is the middle point, we set 42 here for curriculum learning level up
  reward_penalty_degree: 0.000003 # 0.00001
  num_compute_average_epl: 10000

  reward_limit:
    soft_dof_pos_limit: 0.95
    soft_dof_vel_limit: 0.95
    soft_torque_limit: 0.95

    reward_limits_curriculum:
      soft_dof_pos_curriculum: False
      soft_dof_pos_initial_limit: 1.15
      soft_dof_pos_max_limit: 1.15
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 0.00000025
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42

      soft_dof_vel_curriculum: False
      soft_dof_vel_initial_limit: 1.15
      soft_dof_vel_max_limit: 1.25
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 0.00000025
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42

      soft_torque_curriculum: False
      soft_torque_initial_limit: 1.15
      soft_torque_max_limit: 1.25
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 0.00000025
      soft_torque_curriculum_level_down_threshold: 40
      soft_torque_curriculum_level_up_threshold: 42

  reward_penalty_reward_names : [
    "penalty_torques",
    # "penalty_dof_acc",
    # "penalty_dof_vel",
    "penalty_action_rate",
    "limits_dof_pos",
    # "limits_dof_vel",
    "limits_torque",
    "penalty_slippage",
    "penalty_undesired_contact",
    "penalty_ankle_roll",
    "penalty_feet_ori"
    ]